"""
This contains the flow of the chat as a script that the bot uses to remember context and prepare prompts,
its main use is to format the dialog that is to be fed into the OpenAI API.
@author Mari Shenzhen Uy, Mohawk College, Mar 2024
@author Mauricio Canul, Mohawk College, Mar 2024
@version 1.0
"""
from helper import get_json

CONVO_FILE = "topic_prompts.json"
SYSTEM_FILE = "base_prompts.json"
MAX_CONTEXT = 10  # max number of items in context, as to keep token costs low


def create_conversation(history, utterance, filename, target=""):
    """
    Reads a file containing prompt data, then prepares the history into proper prompt form to be appended,
    if the file is of a JSON formatted object, it will extract only the object whose key is the param target

    :return: list containing all the prompts for the OpenAI API
    """
    # We load our dialog prompts from an external file
    dialog = get_json(filename)

    # If we seek a specific target and said key is on the object
    if target != "" and dict(dialog).__contains__(target):
        # Our dialog becomes the value stored within said target
        dialog = dialog.get(target)

    # For each statement found in the history list...
    for statement in history:
        # we append it to our list of prompts
        dialog.append({"role": "user", "content": statement})

    # At the end, we append out last dialog prompt, which is the user's latest utterance
    dialog.append({"role": "user", "content": utterance})

    # We send back this formatted list of prompts
    return dialog


def tune_dialog(dialog: list, json_val: dict, filename: str):
    """
    Function used to do prompt engineering, it is meant to customize the "System" dialog of the
    list of prompts to be passed to the OpenAI API, it is hardcoded to work with the values to
    be generated by the 1st API call, which will discern how relevant to the bot's knowledge domain
    a question is, its tone, and the reasoning for the question

    :param dialog: Current list of prompts, position 0 should be that of "system" and have a key named "content"
    :param json_val: The values to be used to customize the prompt
    :param filename: Target file to get our customization values from
    :return: A list of prompts with the value of one of them fully formatted as required
    """
    # We extract the string to be modified
    tunningString = dialog[0]["content"]

    # We retrieve the values to be used from a JSON file
    file = get_json(filename)

    # If the file contains our "score" object...
    if file.__contains__("score"):
        # We get the score list/array
        scoreArr = file.get("score")
        # We set our score value from the json argument
        score = json_val.get("score")
        # If said value is within the range found in the score list
        if score <= len(scoreArr) and not score < 0:
            # We extract said value and concatenate it
            tunningString += scoreArr[score]
        else:
            # If it is not, then we just extract the value at index 0
            tunningString += scoreArr[0]

    # Then if the file contains our "tone" object...
    if file.__contains__("tone"):
        # We get said dictionary from the json file
        toneObj = dict(file.get("tone"))
        # then we get the "tone" value from the json argument
        tone = json_val.get("tone")
        # If said value is contained within the tone dictionary...
        if toneObj.__contains__(tone):
            # We concatenate it to our string
            tunningString += toneObj.get(tone)
        else:
            # Otherwise we check if our dictionary has a default, and if so, we add said default instead
            if file.__contains__("default"):
                tunningString += toneObj.get("default")

    # Then we finally concatenate the last lines to our tunningString
    tunningString += "You have also figured out that " + json_val.get("explanation") \
                     + " and you may respond accordingly"

    # We set the value of the content to the formatted tunningString
    dialog[0]["content"] = tunningString

    # We return the updated list of prompts
    return dialog


def prepare_history(history):
    """
    Prepare the history into proper prompt format

    :param history:
    :return:
    """
    dialog = []

    for statement in history:
        dialog.append({"role": "user", "content": statement})
    return dialog
